import type { CeviriAnahtari } from '@core/i18n/ceviri-anahtarlari';

import type { CatalogColumn, CatalogConfig, CatalogField } from './catalog-model';

/**
 * Sekiz tanım ekranının alan/sütun tanımı — Blazor sayfalarının form alanları ve tablo sütunları, AYNI sırada.
 * Alan adları sunucu JSON adlarıdır (F9.1 `CatalogDtos*.cs`); sıralanabilir sütunlar sunucunun `Sort` haritasıyla
 * birebir (bilinmeyen alan 400).
 */
const L = (k: string) => `fiyatTarife.alan.${k}` as CeviriAnahtari;
const G = (k: string) => `fiyatTarife.grup.${k}` as CeviriAnahtari;

const code = (maxLength = 32): CatalogField => ({
  name: 'kod',
  label: L('kod'),
  kind: 'text',
  required: true,
  maxLength,
});
const name = (maxLength = 128): CatalogField => ({
  name: 'ad',
  label: L('ad'),
  kind: 'text',
  required: true,
  maxLength,
});
const description = (maxLength = 512): CatalogField => ({
  name: 'aciklama',
  label: L('aciklama'),
  kind: 'text',
  maxLength,
});
const active: CatalogField = { name: 'aktif', label: L('aktif'), kind: 'bool', defaultValue: true };
const col = (field: string, extra: Partial<CatalogColumn> = {}): CatalogColumn => ({
  field,
  ...extra,
});

const RATE_CARDS: CatalogConfig = {
  key: 'tarifeler',
  root: '/api/ui/v1/tarifeler',
  title: 'fiyatTarife.tarifeler.baslik',
  description: 'fiyatTarife.tarifeler.aciklama',
  newTitle: 'fiyatTarife.tarifeler.yeni',
  editTitle: 'fiyatTarife.tarifeler.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    {
      name: 'grup',
      label: L('grup'),
      kind: 'text',
      required: true,
      maxLength: 64,
      suggestion: { endpoint: 'arac-grubu', value: 'kod' },
    },
    { name: 'minGun', label: L('minGun'), kind: 'int', defaultValue: 1 },
    { name: 'maxGun', label: L('maxGun'), kind: 'int', defaultValue: 9999 },
    { name: 'gunlukUcret', label: L('gunlukUcret'), kind: 'money', required: true },
    { name: 'doviz', label: L('doviz'), kind: 'text', maxLength: 3, defaultValue: 'TRY' },
    { name: 'gecerliBas', label: L('gecerliBas'), kind: 'date' },
    { name: 'gecerliBit', label: L('gecerliBit'), kind: 'date' },
    { name: 'tarifeGrubuId', label: L('tarifeGrubu'), kind: 'lookup', lookup: 'tarife-grubu' },
    { name: 'scdwDahil', label: L('scdwDahil'), kind: 'bool', group: G('teminat') },
    { name: 'miniHasarDahil', label: L('miniHasarDahil'), kind: 'bool', group: G('teminat') },
    { name: 'hirsizlikDahil', label: L('hirsizlikDahil'), kind: 'bool', group: G('teminat') },
    { name: 'scdwZorunlu', label: L('scdwZorunlu'), kind: 'bool', group: G('teminat') },
    { name: 'gosterme', label: L('gosterme'), kind: 'bool', group: G('teminat') },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('grup', { sortable: true }),
    col('minGun', { sortable: true }),
    col('maxGun'),
    col('gunlukUcret', { sortable: true, currencyField: 'doviz' }),
    col('gecerliBas'),
    col('gecerliBit'),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

const RATE_GROUPS: CatalogConfig = {
  key: 'tarife-gruplari',
  root: '/api/ui/v1/tarife-gruplari',
  title: 'fiyatTarife.tarifeGruplari.baslik',
  description: 'fiyatTarife.tarifeGruplari.aciklama',
  newTitle: 'fiyatTarife.tarifeGruplari.yeni',
  editTitle: 'fiyatTarife.tarifeGruplari.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    { name: 'oran', label: L('oran'), kind: 'ratio', defaultValue: 0 },
    { name: 'kullaniciAdi', label: L('kullaniciAdi'), kind: 'text', maxLength: 128 },
    { name: 'sifre', label: L('sifre'), kind: 'password', maxLength: 128, hint: L('sifreIpucu') },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('oran', { sortable: true }),
    col('kullaniciAdi'),
    col('sifreVar', { label: L('sifre'), kind: 'bool' }),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

export const COVERAGE_TYPES = [
  'Scdw',
  'MiniHasar',
  'Lcf',
  'Cdw',
  'Pai',
  'Imm',
  'MuafiyetSigortasi',
  'YolYardim',
  'GencSurucu',
  'MaxGuvence',
  'SuperMini',
  'PaketHizmet',
  'KmPaketi',
  'Diger',
] as const;

const COVERAGE_PRODUCTS: CatalogConfig = {
  key: 'sigorta-urunleri',
  root: '/api/ui/v1/sigorta-urunleri',
  title: 'fiyatTarife.sigortaUrunleri.baslik',
  description: 'fiyatTarife.sigortaUrunleri.aciklama',
  newTitle: 'fiyatTarife.sigortaUrunleri.yeni',
  editTitle: 'fiyatTarife.sigortaUrunleri.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    { name: 'adEn', label: L('adEn'), kind: 'text', maxLength: 128 },
    {
      name: 'tur',
      label: L('tur'),
      kind: 'select',
      options: COVERAGE_TYPES,
      optionLabels: 'fiyatTarife.teminatTurleri',
      defaultValue: 'Scdw',
    },
    { name: 'gunlukUcret', label: L('gunlukUcret'), kind: 'money' },
    { name: 'kdvOrani', label: L('kdvYuzde'), kind: 'ratio' },
    { name: 'maxGun', label: L('maxGun'), kind: 'int' },
    { name: 'doviz', label: L('doviz'), kind: 'text', maxLength: 8 },
    { name: 'zorunlu', label: L('zorunlu'), kind: 'bool' },
    description(),
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('tur', { sortable: true }),
    col('gunlukUcret', { sortable: true, currencyField: 'doviz' }),
    col('maxGun'),
    col('zorunlu'),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

const EXTRA_SERVICES: CatalogConfig = {
  key: 'ek-hizmetler',
  root: '/api/ui/v1/ek-hizmetler',
  title: 'fiyatTarife.ekHizmetler.baslik',
  description: 'fiyatTarife.ekHizmetler.aciklama',
  newTitle: 'fiyatTarife.ekHizmetler.yeni',
  editTitle: 'fiyatTarife.ekHizmetler.duzenle',
  titleField: 'kod',
  lockFlag: 'sistem',
  fields: [
    { ...code(), lockedBy: 'sistem' },
    name(),
    { name: 'birimUcret', label: L('birimUcretNet'), kind: 'money', required: true },
    {
      name: 'kdvOrani',
      label: L('kdvOrani'),
      kind: 'ratio',
      defaultValue: 0.2,
      hint: L('kdvOraniIpucu'),
    },
    { name: 'maxGun', label: L('maxGun'), kind: 'int', hint: L('maxGunIpucu') },
    { ...description(), kind: 'textarea' },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('birimUcret', { sortable: true }),
    col('kdvOrani'),
    col('maxGun'),
    col('aciklama'),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

export const APPROVAL_STATES = ['Bekliyor', 'Onayli'] as const;

const dayPrice = (n: string): CatalogField => ({
  name: n,
  label: L(n),
  kind: 'money',
  group: G('fiyat'),
});
const km = (n: string): CatalogField => ({ name: n, label: L(n), kind: 'int', group: G('km') });
const kmFee = (n: string): CatalogField => ({
  name: n,
  label: L(n),
  kind: 'money',
  group: G('km'),
});

const RATE_MATRICES: CatalogConfig = {
  key: 'tarife-matris',
  root: '/api/ui/v1/tarife-matris',
  title: 'fiyatTarife.tarifeMatris.baslik',
  description: 'fiyatTarife.tarifeMatris.aciklama',
  newTitle: 'fiyatTarife.tarifeMatris.yeni',
  editTitle: 'fiyatTarife.tarifeMatris.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    description(),
    {
      name: 'kanal',
      label: L('kanal'),
      kind: 'text',
      maxLength: 64,
      suggestion: { endpoint: 'rezervasyon-kaynagi', value: 'etiket' },
    },
    {
      name: 'sube',
      label: L('sube'),
      kind: 'text',
      maxLength: 64,
      suggestion: { endpoint: 'sube', value: 'etiket' },
    },
    {
      name: 'lokasyon',
      label: L('lokasyon'),
      kind: 'text',
      maxLength: 64,
      hint: L('lokasyonIpucu'),
      suggestion: { endpoint: 'lokasyon', value: 'etiket' },
    },
    {
      name: 'turu',
      label: L('kayitTuru'),
      kind: 'select',
      options: ['Fiyat', 'Kampanya'],
      nullable: true,
    },
    { name: 'kiraSuresi', label: L('kiraSuresi'), kind: 'int', hint: L('kiraSuresiIpucu') },
    {
      name: 'aracGrupKod',
      label: L('aracGrupKod'),
      kind: 'text',
      maxLength: 32,
      suggestion: { endpoint: 'arac-grubu', value: 'kod' },
    },
    { name: 'paraBirimi', label: L('paraBirimi'), kind: 'text', maxLength: 8 },
    { name: 'basTar', label: L('basTar'), kind: 'date' },
    { name: 'bitTar', label: L('bitTar'), kind: 'date' },
    ...['gun1', 'gun2', 'gun3', 'gun4', 'gun5', 'gun6', 'gun7', 'gunHaftalik', 'gunAylik'].map(
      dayPrice,
    ),
    ...[1, 2, 3, 4, 5, 6].flatMap((i) => [km(`km${i}`), kmFee(`km${i}Ucret`)]),
    km('kmHaftalik'),
    kmFee('kmHaftalikUcret'),
    km('kmAylik'),
    kmFee('kmAylikUcret'),
    { name: 'maxEsneklik', label: L('maxEsneklik'), kind: 'ratio' },
    {
      name: 'onayDurumu',
      label: L('onayDurumu'),
      kind: 'select',
      options: APPROVAL_STATES,
      optionLabels: 'fiyatTarife.onayDurumlari',
      defaultValue: 'Bekliyor',
      hint: L('onayIpucu'),
    },
    { name: 'onaylayan', label: L('onaylayan'), kind: 'readonly' },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('kanal', { sortable: true }),
    col('sube'),
    col('aracGrupKod', { sortable: true }),
    col('gun1', { sortable: true, currencyField: 'paraBirimi' }),
    col('onayDurumu', { sortable: true }),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

export const CAMPAIGN_STATES = ['Taslak', 'Planlandi', 'Aktif', 'Pasif', 'Iptal'] as const;
export const DATE_TYPES = ['Rezervasyon', 'Talep'] as const;

const RENTAL_RULES: CatalogConfig = {
  key: 'kira-kurallari',
  root: '/api/ui/v1/kira-kurallari',
  listPath: '/api/ui/v1/kira-kurallari/ara',
  title: 'fiyatTarife.kiraKurallari.baslik',
  description: 'fiyatTarife.kiraKurallari.aciklama',
  newTitle: 'fiyatTarife.kiraKurallari.yeni',
  editTitle: 'fiyatTarife.kiraKurallari.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    description(),
    {
      name: 'kanal',
      label: L('kanal'),
      kind: 'text',
      maxLength: 64,
      suggestion: { endpoint: 'rezervasyon-kaynagi', value: 'etiket' },
    },
    {
      name: 'sube',
      label: L('sube'),
      kind: 'text',
      maxLength: 64,
      suggestion: { endpoint: 'sube', value: 'etiket' },
    },
    {
      name: 'aracGrupKod',
      label: L('aracGrupKod'),
      kind: 'text',
      maxLength: 32,
      suggestion: { endpoint: 'arac-grubu', value: 'kod' },
    },
    { name: 'minGun', label: L('minGun'), kind: 'int' },
    { name: 'maxGun', label: L('maxGun'), kind: 'int' },
    { name: 'iskonto', label: L('iskontoYuzde'), kind: 'ratio' },
    { name: 'haftaSonuFarkOran', label: L('haftaSonuFarkYuzde'), kind: 'ratio' },
    { name: 'sonraOdeOran', label: L('sonraOdeYuzde'), kind: 'ratio' },
    { name: 'hediyeGun', label: L('hediyeGun'), kind: 'int' },
    { name: 'kampanyaMi', label: L('kampanyaMi'), kind: 'bool' },
    { name: 'kampanyaKodu', label: L('kampanyaKodu'), kind: 'text', maxLength: 64 },
    {
      name: 'musteriSegment',
      label: L('musteriSegment'),
      kind: 'text',
      maxLength: 64,
      hint: L('segmentIpucu'),
    },
    { name: 'gecerlilikBas', label: L('gecerlilikBas'), kind: 'date' },
    { name: 'gecerlilikBit', label: L('gecerlilikBit'), kind: 'date' },
    {
      name: 'tarihTipi',
      label: L('tarihTipi'),
      kind: 'select',
      options: DATE_TYPES,
      defaultValue: 'Rezervasyon',
    },
    {
      name: 'kampanyaDurum',
      label: L('kampanyaDurum'),
      kind: 'select',
      options: CAMPAIGN_STATES,
      optionLabels: 'fiyatTarife.kampanyaDurumlari',
      defaultValue: 'Aktif',
    },
    { name: 'sartMetni', label: L('sartMetni'), kind: 'textarea', maxLength: 4000 },
    { name: 'talepBas', label: L('talepBas'), kind: 'date', hint: L('talepIpucu') },
    { name: 'talepBit', label: L('talepBit'), kind: 'date' },
    {
      name: 'promosyonTuru',
      label: L('promosyonTuru'),
      kind: 'select',
      options: ['Coklu', 'Tek'],
      optionLabels: 'fiyatTarife.promosyonTurleri',
      nullable: true,
    },
    {
      name: 'kuponGecerlilik',
      label: L('kuponGecerlilik'),
      kind: 'select',
      options: ['Hepsi', 'SadeceIlkBedel'],
      optionLabels: 'fiyatTarife.kuponGecerlilikleri',
      nullable: true,
    },
    {
      name: 'hesaplamaTipi',
      label: L('hesaplamaTipi'),
      kind: 'select',
      options: ['Oran', 'Serbest'],
      nullable: true,
    },
    { name: 'hizliIslem', label: L('hizliIslem'), kind: 'bool' },
    {
      name: 'haftaGunKisiti',
      label: L('haftaGunKisiti'),
      kind: 'weekdays',
      hint: L('haftaGunIpucu'),
    },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('kanal', { sortable: true }),
    col('sube'),
    col('aracGrupKod'),
    col('minGun'),
    col('maxGun'),
    col('iskonto'),
    col('kampanyaMi'),
    col('tarihTipi'),
    col('gecerlilikBas', { sortable: true }),
    col('gecerlilikBit'),
    col('kampanyaDurum', { sortable: true }),
  ],
  defaultSort: 'kod',
  filters: [
    {
      name: 'durum',
      label: L('kampanyaDurum'),
      kind: 'select',
      options: CAMPAIGN_STATES,
      optionLabels: 'fiyatTarife.kampanyaDurumlari',
    },
    { name: 'tarihTipi', label: L('tarihTipi'), kind: 'select', options: DATE_TYPES },
    { name: 'kampanyaMi', label: L('kampanyaMi'), kind: 'bool' },
    { name: 'kanal', label: L('kanal'), kind: 'text' },
    { name: 'gecerliBas', label: L('gecerliAralikBas'), kind: 'date' },
    { name: 'gecerliBit', label: L('gecerliAralikBit'), kind: 'date' },
  ],
};

const BROKER_BANS: CatalogConfig = {
  key: 'broker-yasaklari',
  root: '/api/ui/v1/broker-yasaklari',
  title: 'fiyatTarife.brokerYasaklari.baslik',
  description: 'fiyatTarife.brokerYasaklari.aciklama',
  newTitle: 'fiyatTarife.brokerYasaklari.yeni',
  editTitle: 'fiyatTarife.brokerYasaklari.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    name(),
    description(),
    {
      name: 'kaynak',
      label: L('kaynak'),
      kind: 'text',
      maxLength: 64,
      hint: L('bosTumu'),
      suggestion: { endpoint: 'rezervasyon-kaynagi', value: 'etiket' },
    },
    {
      name: 'aracGrupKod',
      label: L('aracGrupKodCoklu'),
      kind: 'text',
      maxLength: 32,
      hint: L('virgulIpucu'),
      suggestion: { endpoint: 'arac-grubu', value: 'kod' },
    },
    { name: 'bolge', label: L('bolge'), kind: 'text', maxLength: 64, hint: L('virgulIpucu') },
    { name: 'minGun', label: L('minGun'), kind: 'int', hint: L('minGunYasakIpucu') },
    { name: 'tumSatisKapali', label: L('tumSatisKapali'), kind: 'bool' },
    { name: 'gecerlilikBas', label: L('gecerlilikBas'), kind: 'date' },
    { name: 'gecerlilikBit', label: L('gecerlilikBit'), kind: 'date' },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('ad', { sortable: true }),
    col('kaynak', { sortable: true }),
    col('aracGrupKod'),
    col('bolge'),
    col('minGun'),
    col('tumSatisKapali'),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

const SERVICE_DEFINITIONS: CatalogConfig = {
  key: 'servis-tanimlari',
  root: '/api/ui/v1/servis-tanimlari',
  title: 'fiyatTarife.servisTanimlari.baslik',
  description: 'fiyatTarife.servisTanimlari.aciklama',
  newTitle: 'fiyatTarife.servisTanimlari.yeni',
  editTitle: 'fiyatTarife.servisTanimlari.duzenle',
  titleField: 'kod',
  fields: [
    code(),
    { name: 'aracTipi', label: L('aracTipi'), kind: 'text', required: true, maxLength: 100 },
    { name: 'bakimKm', label: L('bakimKm'), kind: 'int', required: true },
    description(),
    { name: 'marka', label: L('marka'), kind: 'text', maxLength: 100 },
    { name: 'tip', label: L('tip'), kind: 'text', maxLength: 100 },
    { name: 'yakit', label: L('yakit'), kind: 'text', maxLength: 32 },
    { name: 'vites', label: L('vites'), kind: 'text', maxLength: 32 },
    active,
  ],
  columns: [
    col('kod', { sortable: true }),
    col('aracTipi', { sortable: true }),
    col('marka', { sortable: true }),
    col('tip'),
    col('yakit'),
    col('vites'),
    col('bakimKm', { sortable: true }),
    col('aciklama'),
    col('aktif', { sortable: true }),
  ],
  defaultSort: 'kod',
};

export const CATALOGS: Readonly<Record<string, CatalogConfig>> = {
  [RATE_CARDS.key]: RATE_CARDS,
  [RATE_GROUPS.key]: RATE_GROUPS,
  [COVERAGE_PRODUCTS.key]: COVERAGE_PRODUCTS,
  [EXTRA_SERVICES.key]: EXTRA_SERVICES,
  [RATE_MATRICES.key]: RATE_MATRICES,
  [RENTAL_RULES.key]: RENTAL_RULES,
  [BROKER_BANS.key]: BROKER_BANS,
  [SERVICE_DEFINITIONS.key]: SERVICE_DEFINITIONS,
};
